### ISSUE TITLE
Show information about cell in the taskpane

### ISSUE THREAD

**Issue by VAISHALI-DHANOA** [JKU-ICG/fuzzy-spreadsheet#35]
- [x] Show Impact information
- [x] Show Likelihood information
- [x] Show mean information
- [x] Show variance information
- [x] Show relationship information
- [x] Show Spread information
- [x] Change MIN and MAX value from Impact to real min and max value according to the color encoding
- [x] Update likelihood information within the taskpane within the What-If Analysis

**Comment by ConnyWalchshofer** [comment]
Add horizontal lines as separator again to the taskpane --> see original pull request
