### ISSUE TITLE
Change spread encoding to a heatmap encoding

### ISSUE THREAD

**Issue by VAISHALI-DHANOA** [JKU-ICG/fuzzy-spreadsheet#54]
Change spread encoding to a heatmap encoding
https://www.nytimes.com/interactive/2020/world/coronavirus-maps.html

![grafik](https://user-images.githubusercontent.com/2544506/77297054-0711ac80-6ce9-11ea-9fb8-8e5083262eca.png)

**Comment by ConnyWalchshofer** [comment]
Adapt size of distribution within the taskpane. --> Reduce height

**Comment by ConnyWalchshofer** [comment]
Add legend for the cell content
