### ISSUE TITLE
What-If Analysis

### ISSUE THREAD

**Issue by ConnyWalchshofer** [JKU-ICG/fuzzy-spreadsheet#57]
When starting the What-If analysis and changing values. Arrow indicators show if a cell content was positively or negatively affected by a value change.

In the following screenshot, I showed 
- influenced by the reference cell
- 2nd degree of neighborhood
- Impact
- Likelihood
- Relationship
- Distribution

The value 31,2 shows a +2 and the cell with the content 12.7 shows a +0.1.
- [x] Add sign (+) or (-)
- [x] Change arrows to triangles
- [x] Adapt the Keep new values option

- Why is the relationship / degree of neighborhood not shown for the cell with the content 31.2? 
- Overlay of information: Arrow indicator is positioned over the relationship glyph and the numeric indicator 0.1 is overlapping with the impact, likelihood, and distribution information. 

![image](https://user-images.githubusercontent.com/22545084/77298746-adf74800-6ceb-11ea-9b75-c60f1c7e5cc4.png)

**Comment by VAISHALI-DHANOA** [comment]
![grafik](https://user-images.githubusercontent.com/2544506/77826754-95cf6080-7111-11ea-9612-74845781bd35.png)
This is how it looks like now.
