### ISSUE TITLE
Distribution Cell and Taskpane

### ISSUE THREAD

**Issue by ConnyWalchshofer** [JKU-ICG/fuzzy-spreadsheet#58]
- [x] Add legend for color encoding
- [x] Add white horizontal line to distinguish have a small space between actual and changed heatmap
- [x] Position distributions in taskpane not next to each other but as in the cell below each other
- [x] Add mean
- [x] Add variance

**Comment by VAISHALI-DHANOA** [comment]
https://d3-legend.susielu.com/
