### ISSUE TITLE
Reference Cell

### ISSUE THREAD

**Issue by ConnyWalchshofer** [JKU-ICG/fuzzy-spreadsheet#61]
Remove gray background-color from reference cell and add cell border to indicate the reference cell.

- [x] Remove background-color
- [x] Add border-color for cell (color?) (width: 1px or 2px)
- [ ] Add Column/Row letter/number within the taskpane, e.g., **$R$2** (same counts for the What-If Analysis, when a "compared cell" it selected, the taskpane nees to indicate both cells (reference, and compared with cell)

**Comment by VAISHALI-DHANOA** [comment]
During what-if analysis we do not compare two cells. Besides I have changed the encoding of the reference cell & we may not need this "button" for the reference cell after all
