### ISSUE TITLE
Unselect all visual encodings

### ISSUE THREAD

**Issue by ConnyWalchshofer** [JKU-ICG/fuzzy-spreadsheet#66]
When I marked a cell as a reference cell and show 

- influencing cells
- 1st degree of neighborhood
- Impact
- Likelihood
- Relationship
- Distribution 

and I simply no longer want to show any of these visual encodings, I expect that there is a checkbox where I can unselect all tasks at once.

**Current situation**
I manually have to unselect all visual encodings in the taskpane. THus, leading to 5 clicks.

**Expected situation**
When all visual encodings are shown, I expect that a "Show all" checkbox is incorporated to either show all encodings or no encoding. Thus, leading to an unselect of all checkboxes.

**Comment by VAISHALI-DHANOA** [comment]
We discussed this already and Marc discarded the issue in a meeting, therefore I removed it from the issues list.
