### ISSUE TITLE
Taskpane adaption

### ISSUE THREAD

**Issue by ConnyWalchshofer** [JKU-ICG/fuzzy-spreadsheet#77]
- [x] horizontal lines : To be dealt with later, when all other changes are made.
- [x] relational information
  - [x] influencing the reference cell in a proper row + glyphs
  - [x] influenced by the reference cell in a proper row + glyphs
  - [x] change marker from dashed to solid line and green
  - [ ] add "Hide relationship markers": What to do when you want to see the markers?
- [x] neighborhood
  - [x] add zero neighborhood relationship in orange
- [x] Impact
  - [x] svg in new row instead of column
  - [x]  initial value on top, green
  - [x] new value bottom, pink
  - [x] color scale from red-green to red - blue
  - [x] add sign to negative impact values
- [x] Likelihood
  - [x] svg in new row instead of column
  - [x] Change marker from horizontal line to border, no filling
- [x] Distribution
  - [x] add 2x2 table
  - [x] change color encoding
  - [x] remove M / SD from svg itself, instead retrieve the value on the right side
  - [x] reduce line width of M / SD
  - [x]  reduce height for y-axis --> "compress"
  - [x]  ....
- [x] What-If Analysis
  - [x]  Creating 2 columns for keep or undo changes

**Comment by VAISHALI-DHANOA** [comment]
What shade of green should we use?
