### ISSUE TITLE
Have a focus cell and a reference cell

### ISSUE THREAD

**Issue by VAISHALI-DHANOA** [JKU-ICG/fuzzy-spreadsheet#9]
Allow the user to have multiple focus cell. However, issues such as overlapping of impact and likelihood, need to be addressed

**Comment by ConnyWalchshofer** [comment]
When a reference cell will be changed, then

1. delete all figures created - dependent on the previous reference cell
2. update new reference cell information (color cell, and check relationship information) 
3. add visual encoding for all tasks that are checked (checkbox = true) for the new reference cell
4. draw glyphs/charts based on new reference cell
